### ISSUE TITLE
Confusion regarding outputs from first and second module

### ISSUE THREAD

**Issue by Mishra1995** [lucidrains/muse-maskgit-pytorch#10]
Hi,

Thanks for implementing and open-sourcing the code for this T2I model.

I ran the first snippet of the code where the objective was to train a VQGanVAE model. 

After training the VQGanVAE model for 50K iterations, I trained the MaskGIT module, although the set of images and texts passed into the training of MaskGIT were less compared to the first module training since I was getting memory issue.

Nevertheless, I passed 10 images and the corresponding texts to train the super resolution GIT and saved the images. The following are few of the images that I am getting.

![maskgit_2_](https://user-images.githubusercontent.com/107555279/212602690-4bd367ac-5ef1-49a7-9eef-6ad6f2cc237c.jpg)
![maskgit_0_](https://user-images.githubusercontent.com/107555279/212602682-4f36c302-d55d-4ac6-b5b3-fc898149dbbc.jpg)
![maskgit_1_](https://user-images.githubusercontent.com/107555279/212602687-ec7bd647-c6da-4976-81dc-8656e84c7596.jpg)

My query is that whether this is the correct process that I am following? Do I need to train on more images to get the image corresponding to the text?

Thanks!

**Comment by lucidrains** [comment]
@Mishra1995 ohh, @lonzi found a bug in the other issue, do you want to retry with 0.0.19?

also, what kind of results are you seeing with vqgan-vae?

**Comment by Mishra1995** [comment]
Thanks @lucidrains, I have updated the repo with 0.0.19 and repeating the steps again. I will update in this thread once the training is complete!

**Comment by enesgrahovac** [comment]
Hi @Mishra1995, I'm also spending time training this. Would you be open to chatting as we both work on this? My email is enesxgrahovac@gmail.com

**Comment by enesgrahovac** [comment]
@lucidrains I'm still training the VAE. 

I'm training with:
- 50 images
- size=64
- batch_size = 4,
- grad_accum_every = 8,
- num_train_steps = 50000

Here's the results at 17,000 training steps

<img width="386" alt="image" src="https://user-images.githubusercontent.com/34563104/213475711-3606731d-217c-4bf2-b6bc-c2666f173c7f.png">

Does there seem to be a problem with this training configuration, or is this supposed to improve around the 50,000'th step?
