### ISSUE TITLE
What is minimum VRAM for running demo?

### ISSUE THREAD

**Issue by treasuraid** [lucidrains/muse-maskgit-pytorch#16]
I'm trying to run demo on my RTX-3080 but it shows lack of VRAM..

**Comment by longsc2603** [comment]
Hello, I have the same question, my GPU is also RTX 3080 and it always shows cuda out of memory, even if I set batch_size=1 and image_size=128. I see that you closed this issue as competed so maybe you have the answer. Thank you.
