### ISSUE TITLE
Can this repo be used to train MaskGIT as in the original publication?

### ISSUE THREAD

**Issue by OhGreat** [lucidrains/muse-maskgit-pytorch#26]
Hello, I am interested in training a MaskGIT model, without any text conditioning and all the parts relevant to Muse. Is that possible?

**Comment by lucidrains** [comment]
@OhGreat you can use the code at [x-transformers](https://github.com/lucidrains/x-transformers/blob/main/x_transformers/nonautoregressive_wrapper.py) (was experimenting with text there, but should work on any codebook id from any autoencoder)
