### ISSUE TITLE
Can you release the official trained model?

### ISSUE THREAD

**Issue by JoonHyeokJ** [lucidrains/muse-maskgit-pytorch#34]
Hello!
I've read the paper of MUSE, and I think the result is so amazing!
So I want to try this amazing model.
Can you release the official pretrained weight of vae and maskgit?

**Comment by korakoe** [comment]
> Hello!
> I've read the paper of MUSE, and I think the result is so amazing!
> So I want to try this amazing model.
> Can you release the official pretrained weight of vae and maskgit?

This isn’t the official implementation, so there aren’t any weights, however efforts are being made to try and train it
