### ISSUE TITLE
Better way to handle Classifier-free guidance with flash_attn

### ISSUE THREAD

**Issue by sukun1045** [lucidrains/muse-maskgit-pytorch#37]
Hi, in this repo, the classifier-free guidance is handled by setting a `context_mask` based on the dropout probability.

https://github.com/lucidrains/muse-maskgit-pytorch/blob/849bbd87f975255943349690a17a40f0103521d9/muse_maskgit_pytorch/muse_maskgit_pytorch.py#L306C1-L310C47

However, some rows of the `context_mask` could become all `False` and I found that if we use `flash_attn`, the `F.scaled_dot_product_attention` will generate `NaN` values. 

I found that you have handled something similar in the x-transformer repo regarding the [issue](https://github.com/lucidrains/x-transformers/issues/187)

https://github.com/lucidrains/x-transformers/blob/4f9775ba62ea65ba46cc496f13adad827605537c/x_transformers/attend.py#L201

But it seems like that can only handle the case for causal attention and the particular row of the mask. If we are working on maskgit where the attention is non-causal and sometimes `context_mask` could be False anywhere, then the current version of `F.scaled_dot_product_attention` will still generate `NaN`.

Therefore I am wondering whether there is a better way to support the `flash_attn` with classifier-free guidance.

Thank you.

**Comment by lucidrains** [comment]
@sukun1045 hey Kun

thank you for your interest in the repository

i actually avert that issue through a technique where i append [a key / value](https://github.com/lucidrains/muse-maskgit-pytorch/blob/849bbd87f975255943349690a17a40f0103521d9/muse_maskgit_pytorch/muse_maskgit_pytorch.py#L155) that is always attended to for cross attention. the appending of these learned key / values goes back to [an old Meta AI paper](https://www.arxiv-vanity.com/papers/1907.01470/) where they were trying to replace feedforwards. however, nowadays i think it makes sense to always append a few of these key / values to allow attention to [attend to nothing](https://arxiv.org/abs/2306.12929). incidentally it fixes this edge case of a row entirely masked out

**Comment by sukun1045** [comment]
I see. Yeah, I tried to use Attention in x-trasnformer package and missed that in this repo. If I understand correctly, I could simply set the Flag `self.add_zero_kv` as `True` when I have `context_mask` in the [x-transformer version](https://github.com/lucidrains/x-transformers/blob/4f9775ba62ea65ba46cc496f13adad827605537c/x_transformers/attend.py#L284). Is that correct?

Thanks again for your reply.

**Comment by lucidrains** [comment]
@sukun1045 if using `x-transformers` you would set `attn_num_mem_kv` > 0

**Comment by lucidrains** [comment]
people give it all sort of names (memories, registers, null kv) but its all the same

**Comment by sukun1045** [comment]
Got it. Thanks!
