### ISSUE TITLE
T5 bug?

### ISSUE THREAD

**Issue by lqniunjunlper** [lucidrains/muse-maskgit-pytorch#38]
Why use this at line#93 in t5.py?
   
encoded_text = encoded_text.masked_fill(attn_mask[..., None], 0.)

**Comment by lqniunjunlper** [comment]
This step will change all text embeddings with MASK=True to 0.
Should use attn_mask = ~attn_mask.bool()?

**Comment by lucidrains** [comment]
@lqniunjunlper 🤦  yes, thank you
