### ISSUE TITLE
Gumbel Sample

### ISSUE THREAD

**Issue by pranoyr** [lucidrains/muse-maskgit-pytorch#42]
Since top_k threshold is 0.9 ,  gumbel sample will always take the indice with max probability, right?  I guess temperature has no effect here?

So , the sampling here is argmax only?

**Comment by lucidrains** [comment]
@pranoyr a [gumbel noise](https://github.com/lucidrains/muse-maskgit-pytorch/blob/main/muse_maskgit_pytorch/muse_maskgit_pytorch.py#L411) is added

**Comment by pranoyr** [comment]
When i change the top_k threshold to 0.5,  I am getting indices different from argmax while performing gumbel sampling. But when top_k = 0.9. Gumbel samling gives me exactly the  same result as argmax.

**Comment by pranoyr** [comment]
Got it . I did something wrong!

**Comment by lucidrains** [comment]
it is my bad, as typically one sets the k value. I'll correct this soon, that function has bad naming

**Comment by pranoyr** [comment]
Thank you for your reply 👍.
