### ISSUE TITLE
Negative prompting from the Muse paper?

### ISSUE THREAD

**Issue by LinkAnJarad** [lucidrains/muse-maskgit-pytorch#7]
Would it be possible to implement negative prompting as described in section 2.7 in the paper? In the paper, the final tokens are calculated as $\ell_g = (1+t)\ell_c-t\ell_u$, and negative prompting would is done "by replacing the uncondtional logit $\ell_u$ with a logit conditioned on a negative prompt."

**Comment by lucidrains** [comment]
@LinkAnJarad ok [done](https://github.com/lucidrains/muse-maskgit-pytorch/commit/5bdcefa73f623632ac9c6c221859150f04e54498)
